[package]
name = "tea-data-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
glob = "0.3"
serde = { version = "1.0", features = ["derive"] }
polars = { version = "0.41", features = ["polars-io", "ipc", "lazy"] }
derive_more = { version = "0.99", features = ["from", "is_variant"] }
anyhow = "1.0"
rayon = "1.10"
ctor = "0.2"
regex = "1.10"
parking_lot = "0.12"
itertools = "0.13"
factor-macro = { path = "./factor-macro" }

[dependencies.tea_strategy]
git = "https://github.com/Teamon9161/tea_strategy.git"
branch = "master"
default-features = false
features = ['pl', "time"]
