[path_finder.main_path]
rq = "C://working/data"
coin = "C:/coin/data"
ddb-xbond = "C:/working/data/ddb-xbond"
ddb-future = "C:/working/data/ddb-future"

[path_finder.type_source]
future = "rq"
stock_index = "rq"
national_debt = "rq"
rf = "rq"
coin_future = "coin"
coin_spot = "coin"
ddb-xbond = "ddb-xbond"
ddb-future = "ddb-future"

[loader.rename.future]
info = { underlying_symbol = "symbol" }
compose = { datetime = "time", total_turnover = "amt" }

[loader.rename.future.min]
underlying_symbol = "symbol"
datetime = "time"
total_turnover = "amt"

[loader.rename.future.daily]
underlying_symbol = "symbol"
date = "time"
total_turnover = "amt"

[loader.rename.future.min.subhot]
datetime = "time"
total_turnover = "amt"
order_book_id = "dominant_id"

[loader.rename.future.daily.subhot]
date = "time"
total_turnover = "amt"
order_book_id = "dominant_id"

[loader.rename.ddb-xbond.tick]
code = "symbol"
source_time = "time"
bid_price1 = "bid1"
bid_size1 = "bid1_vol"
bid_yield1 = "bid1_ytm"
ask_price1 = "ask1"
ask_size1 = "ask1_vol"
ask_yield1 = "ask1_ytm"
bid_price2 = "bid2"
bid_size2 = "bid2_vol"
bid_yield2 = "bid2_ytm"
bid_price3 = "bid3"
bid_size3 = "bid3_vol"
bid_yield3 = "bid3_ytm"
bid_price4 = "bid4"
bid_size4 = "bid4_vol"
bid_yield4 = "bid4_ytm"
bid_price5 = "bid5"
bid_size5 = "bid5_vol"
bid_yield5 = "bid5_ytm"
ask_price2 = "ask2"
ask_size2 = "ask2_vol"
ask_yield2 = "ask2_ytm"
ask_price3 = "ask3"
ask_size3 = "ask3_vol"
ask_yield3 = "ask3_ytm"
ask_price4 = "ask4"
ask_size4 = "ask4_vol"
ask_yield4 = "ask4_ytm"
ask_price5 = "ask5"
ask_size5 = "ask5_vol"
ask_yield5 = "ask5_ytm"

[loader.rename.ddb-future.tick]
datetime = "time"
bid_price1 = "bid1"
bid_size1 = "bid1_vol"
ask_price1 = "ask1"
ask_size1 = "ask1_vol"
bid_price2 = "bid2"
bid_size2 = "bid2_vol"
bid_price3 = "bid3"
bid_size3 = "bid3_vol"
bid_price4 = "bid4"
bid_size4 = "bid4_vol"
bid_price5 = "bid5"
bid_size5 = "bid5_vol"
ask_price2 = "ask2"
ask_size2 = "ask2_vol"
ask_price3 = "ask3"
ask_size3 = "ask3_vol"
ask_price4 = "ask4"
ask_size4 = "ask4_vol"
ask_price5 = "ask5"
ask_size5 = "ask5_vol"

[loader.rename.ddb-xbond.trade]
last_px = "order_price"
code = "symbol"
last_yield = "order_ytm"
last_size = "order_amt"
