[path_finder.main_path]
rq = "D://working/data"
coin = "C:/coin/data"
ddb-xbond = "D:/working/data/ddb-xbond"
ddb-future = "D:/working/data/ddb-future"
sse-bond = "D:/working/data/sse-bond"

[path_finder.type_source]
future = "rq"
stock_index = "rq"
national_debt = "rq"
rf = "rq"
coin_future = "coin"
coin_spot = "coin"
ddb-xbond = "ddb-xbond"
ddb-future = "ddb-future"
sse-bond = "sse-bond"

[loader.rename.future]
info = { underlying_symbol = "symbol" }
compose = { datetime = "time", total_turnover = "amt" }

[loader.rename.future.min]
underlying_symbol = "symbol"
datetime = "time"
total_turnover = "amt"

[loader.rename.future.daily]
underlying_symbol = "symbol"
date = "time"
total_turnover = "amt"

[loader.rename.future.min.subhot]
datetime = "time"
total_turnover = "amt"
order_book_id = "dominant_id"

[loader.rename.future.daily.subhot]
date = "time"
total_turnover = "amt"
order_book_id = "dominant_id"

[loader.rename.ddb-xbond.tick]
code = "symbol"
source_time = "time"
bid_price1 = "bid1"
bid_size1 = "bid1_vol"
bid_yield1 = "bid1_ytm"
ask_price1 = "ask1"
ask_size1 = "ask1_vol"
ask_yield1 = "ask1_ytm"
bid_price2 = "bid2"
bid_size2 = "bid2_vol"
bid_yield2 = "bid2_ytm"
bid_price3 = "bid3"
bid_size3 = "bid3_vol"
bid_yield3 = "bid3_ytm"
bid_price4 = "bid4"
bid_size4 = "bid4_vol"
bid_yield4 = "bid4_ytm"
bid_price5 = "bid5"
bid_size5 = "bid5_vol"
bid_yield5 = "bid5_ytm"
ask_price2 = "ask2"
ask_size2 = "ask2_vol"
ask_yield2 = "ask2_ytm"
ask_price3 = "ask3"
ask_size3 = "ask3_vol"
ask_yield3 = "ask3_ytm"
ask_price4 = "ask4"
ask_size4 = "ask4_vol"
ask_yield4 = "ask4_ytm"
ask_price5 = "ask5"
ask_size5 = "ask5_vol"
ask_yield5 = "ask5_ytm"

[loader.rename.ddb-future.tick]
datetime = "time"
bid_price1 = "bid1"
bid_size1 = "bid1_vol"
ask_price1 = "ask1"
ask_size1 = "ask1_vol"
bid_price2 = "bid2"
bid_size2 = "bid2_vol"
bid_price3 = "bid3"
bid_size3 = "bid3_vol"
bid_price4 = "bid4"
bid_size4 = "bid4_vol"
bid_price5 = "bid5"
bid_size5 = "bid5_vol"
ask_price2 = "ask2"
ask_size2 = "ask2_vol"
ask_price3 = "ask3"
ask_size3 = "ask3_vol"
ask_price4 = "ask4"
ask_size4 = "ask4_vol"
ask_price5 = "ask5"
ask_size5 = "ask5_vol"

[loader.rename.ddb-xbond.trade]
last_px = "order_price"
code = "symbol"
last_yield = "order_ytm"
last_size = "order_vol"

[loader.rename.sse-bond.tick]
Symbol = "symbol"
TradingDate = "trading_date"
TradingTime = "time"
PreClosePrice = "prev_close"
OpenPrice = "daily_open"
HighPrice = "daily_high"
LowPrice = "daily_low"
LastPrice = "last_price"
TradeStatus = "trade_status"
SellPrice01 = "ask1"
SellPrice02 = "ask2"
SellPrice03 = "ask3"
SellPrice04 = "ask4"
SellPrice05 = "ask5"
SellPrice06 = "ask6"
SellPrice07 = "ask7"
SellPrice08 = "ask8"
SellPrice09 = "ask9"
SellPrice10 = "ask10"
BuyPrice01 = "bid1"
BuyPrice02 = "bid2"
BuyPrice03 = "bid3"
BuyPrice04 = "bid4"
BuyPrice05 = "bid5"
BuyPrice06 = "bid6"
BuyPrice07 = "bid7"
BuyPrice08 = "bid8"
BuyPrice09 = "bid9"
BuyPrice10 = "bid10"
SellVolume01 = "ask1_vol"
SellVolume02 = "ask2_vol"
SellVolume03 = "ask3_vol"
SellVolume04 = "ask4_vol"
SellVolume05 = "ask5_vol"
SellVolume06 = "ask6_vol"
SellVolume07 = "ask7_vol"
SellVolume08 = "ask8_vol"
SellVolume09 = "ask9_vol"
SellVolume10 = "ask10_vol"
BuyVolume01 = "bid1_vol"
BuyVolume02 = "bid2_vol"
BuyVolume03 = "bid3_vol"
BuyVolume04 = "bid4_vol"
BuyVolume05 = "bid5_vol"
BuyVolume06 = "bid6_vol"
BuyVolume07 = "bid7_vol"
BuyVolume08 = "bid8_vol"
BuyVolume09 = "bid9_vol"
BuyVolume10 = "bid10_vol"
TotalNo = "total_count"
TotalVolume = "total_vol"
TotalAmount = "total_amt"
TotalBuyNo = "total_buy_count"
TotalSellNo = "total_sell_count"
TotalBuyOrderVolume = "total_buy_vol"
TotalSellOrderVolume = "total_sell_vol"
BuyOrderNo = "buy_count"
SellOrderNo = "sell_count"
BondWtAvgBuyPrice = "order_buy_price"
BondWtAvgSellPrice = "order_sell_price"
IOPV = "iopv"
YTM = "ytm"
ETFBuyNo = "etf_buy_count"
ETFBuyVolume = "etf_buy_vol"
ETFBuyAmount = "etf_buy_amt"
ETFSellNo = "etf_sell_count"
ETFSellVolume = "etf_sell_vol"
ETFSellAmount = "etf_sell_amt"
WithdrawBuyNo = "withdraw_buy_count"
WithdrawBuyVolume = "withdraw_buy_vol"
WithdrawBuyAmount = "withdraw_buy_amt"
WithdrawSellNo = "withdraw_sell_count"
WithdrawSellVolume = "withdraw_sell_vol"
WithdrawSellAmount = "withdraw_sell_amt"
