[path_finder.main_path]
rq = "C://working/data"
coin = "C:/coin/data"
xbond = "C:/working/ttrd/output"
ddb-xbond = "C:/working/data/ddb-xbond"
ddb-future = "C:/working/data/ddb-future"

[path_finder.type_source]
future = "rq"
stock_index = "rq"
national_debt = "rq"
rf = "rq"
coin_future = "coin"
coin_spot = "coin"
xbond = "xbond"
ddb-xbond = "ddb-xbond"
ddb-future = "ddb-future"

[loader.rename.future]
info = { underlying_symbol = "symbol" }
compose = { datetime = "time", total_turnover = "amt" }

[loader.rename.future.min]
underlying_symbol = "symbol"
datetime = "time"
total_turnover = "amt"

[loader.rename.future.daily]
underlying_symbol = "symbol"
date = "time"
total_turnover = "amt"

[loader.rename.future.min.subhot]
datetime = "time"
total_turnover = "amt"
order_book_id = "dominant_id"

[loader.rename.future.daily.subhot]
date = "time"
total_turnover = "amt"
order_book_id = "dominant_id"

[loader.rename.xbond.tick]
SECURITYID = "symbol"
BidYTM1 = "b1_ytm"
BidYTM2 = "b2_ytm"
BidYTM3 = "b3_ytm"
BidYTM4 = "b4_ytm"
BidYTM5 = "b5_ytm"
BidPrice1 = "b1"
BidPrice2 = "b2"
BidPrice3 = "b3"
BidPrice4 = "b4"
BidPrice5 = "b5"
BidVolume1 = "b1_v"
BidVolume2 = "b2_v"
BidVolume3 = "b3_v"
BidVolume4 = "b4_v"
BidVolume5 = "b5_v"
AskYTM1 = "a1_ytm"
AskYTM2 = "a2_ytm"
AskYTM3 = "a3_ytm"
AskYTM4 = "a4_ytm"
AskYTM5 = "a5_ytm"
AskPrice1 = "a1"
AskPrice2 = "a2"
AskPrice3 = "a3"
AskPrice4 = "a4"
AskPrice5 = "a5"
AskVolume1 = "a1_v"
AskVolume2 = "a2_v"
AskVolume3 = "a3_v"
AskVolume4 = "a4_v"
AskVolume5 = "a5_v"
I_NAME = "name"
PRICE = "price"
YTM = "ytm"
TRDFV = "trdfv"


[loader.rename.ddb-xbond.tick]
code = "symbol"
source_time = "time"
bid_price1 = "b1"
bid_size1 = "b1_v"
bid_yield1 = "b1_y"
ask_price1 = "a1"
ask_size1 = "a1_v"
ask_yield1 = "a1_y"
bid_price2 = "b2"
bid_size2 = "b2_v"
bid_yield2 = "b2_y"
bid_price3 = "b3"
bid_size3 = "b3_v"
bid_yield3 = "b3_y"
bid_price4 = "b4"
bid_size4 = "b4_v"
bid_yield4 = "b4_y"
bid_price5 = "b5"
bid_size5 = "b5_v"
bid_yield5 = "b5_y"
ask_price2 = "a2"
ask_size2 = "a2_v"
ask_yield2 = "a2_y"
ask_price3 = "a3"
ask_size3 = "a3_v"
ask_yield3 = "a3_y"
ask_price4 = "a4"
ask_size4 = "a4_v"
ask_yield4 = "a4_y"
ask_price5 = "a5"
ask_size5 = "a5_v"
ask_yield5 = "a5_y"

[loader.rename.ddb-future.tick]
datetime = "time"
bid_price1 = "b1"
bid_size1 = "b1_v"
ask_price1 = "a1"
ask_size1 = "a1_v"
bid_price2 = "b2"
bid_size2 = "b2_v"
bid_price3 = "b3"
bid_size3 = "b3_v"
bid_price4 = "b4"
bid_size4 = "b4_v"
bid_price5 = "b5"
bid_size5 = "b5_v"
ask_price2 = "a2"
ask_size2 = "a2_v"
ask_price3 = "a3"
ask_size3 = "a3_v"
ask_price4 = "a4"
ask_size4 = "a4_v"
ask_price5 = "a5"
ask_size5 = "a5_v"
